### ISSUE TITLE
Bridge Constructor

### ISSUE THREAD

**Issue by vinstic** [glasklart/hd#192]
**App Name:** Bridge Constructor
**Bundle ID:** com.headupgames.bridgeconstructor
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=503190232">503190232</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/bridge-constructor/id503190232?mt=8&uo=4">https://itunes.apple.com/us/app/bridge-constructor/id503190232?mt=8&uo=4</a>
**App Version:** 3.7
**Seller:** Headup Games GmbH & Co. KG
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/headup-games-gmbh-co-kg/id503190235?uo=4>© Headup Games GmbH & Co KG</a>
**Supported Devices:** iPhone-3GS, iPadWifi, iPad3G, iPodTouchThirdGen, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/c5/c6/58/c5c65836-2cac-a27a-eca2-7a11e75b1b34/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17033671/8d0bdf4e-4f7f-11e6-8a55-92ce00876e19.png)

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/13546328/cbfedc52-e2aa-11e5-9369-350e5128da8c.png)
https://cloud.githubusercontent.com/assets/2068130/13546328/cbfedc52-e2aa-11e5-9369-350e5128da8c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/13546331/d94caac4-e2aa-11e5-9bc2-3a62c00ba17e.png

**Comment by Anuskuss** [comment]
@dreamnet Could you make the lines of the ropes thicker?

**Comment by dreamnet** [comment]
@Anuskuss This is hard, because the lines of the ropes are all different, according to the original icon. Here is my best try:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/17033671/8d0bdf4e-4f7f-11e6-8a55-92ce00876e19.png)
https://cloud.githubusercontent.com/assets/2068130/17033671/8d0bdf4e-4f7f-11e6-8a55-92ce00876e19.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/17033689/9c902736-4f7f-11e6-9758-d82a92cd1613.png

**Comment by Anuskuss** [comment]
I like it :+1:
