### ISSUE TITLE
AirBlue Sharing

### ISSUE THREAD

**Issue by andrenor** [glasklart/hd#2456]
**App Name:** AirBlue Sharing
**Bundle ID:** com.if0rce.AirBlueSharing
**iTunes ID:** none (Cydia app)
**iPhone Icon Name:** Icon.png
**Icon Names:** Icon.png
**Original Artwork:**
<img src="https://f.cloud.github.com/assets/3758639/502133/0936794e-bca8-11e2-8f97-a5c13f94880c.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5838291/ab328cb4-a186-11e4-8c87-d8cf81032604.png)

**Comment by dreamnet** [comment]
Bundle id has changed from `com.if0rce.blued-obex` to `com.ericday.blued-obex`.

**Comment by dreamnet** [comment]
A source for this one would be nice.

**Comment by MagnaMike** [comment]
Sorry @dreamnet I don't think I have my icon sources anymore (moved to a new computer a while ago). I can check tonight though, maybe I uploaded them to my Dropbox or Google Drive.

**Comment by dreamnet** [comment]
@MagnaMike OK, thank's, I will check the Dropbox.

**Comment by MagnaMike** [comment]
@dreamnet Oh, maybe I put them there (It's been a while!), but I was talking about my own personal Dropbox files.

**Comment by dreamnet** [comment]
@MagnaMike Ah, OK, could not find anything in our Dropbox, but don't to search any longer, I remade it:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/5838125/5410a624-a185-11e4-877b-b7623e068687.png)
https://cloud.githubusercontent.com/assets/2068130/5838125/5410a624-a185-11e4-877b-b7623e068687.png
Source:
https://cloud.githubusercontent.com/assets/2068130/5838133/6532c086-a185-11e4-8005-c73ff484447a.png
I think it looks nearly good as yours... :wink:

**Comment by MagnaMike** [comment]
@dreamnet I ended up checking, my source files are lost forever. :grin:  But it doesn't really matter, they were poorly made (I mainly just made my icons using the eraser tool on photoshop...). I've been trying to learn how to use illustrator lately because I've been thinking about releasing an android theme (It's not as complicated to make them as I once thought). Maybe I'll start making Glasklart icons again now too. 

Anyway, I think your icon is nicer, plus that source file is beautiful. :astonished:

**Comment by dreamnet** [comment]
@MagnaMike It would be very nice too see you here again Mike!
Quick Illustrator tips... hm. Well I have to say that you can easily use the trace function of Illustrator for the simpler icons. Just open the 1024x1024px original image and trace it - then remove everting that schould be transparent and make all remaining parts black (grayscale, 100%). You have to play around a bit with the trace options too get good results.
I always save the finished icon as .svg and export it to .png too (make sure to select "Use Artboard" in the export btw. save dialog). You can find all svg's I made on my website.
If you have a "relative simple" icon (as this one here) then it's often better to draw a new icon over the original image than to trace it. Sometimes this is faster and you will get better results.
If I make a border or round image corners I always use the rounded rectangle tool with 1024x1024px and a border radius of 180px.
I also have a simple Photoshop script ready, that generates automatic Glasklart icons from a 1024x1024px png source file in three different sizes (iPhone, iPad and iPhone @3x). I will contribute this script shortly on my Github account here.

**Comment by MagnaMike** [comment]
@dreamnet So is using that script something you will want to be done when fulfilling icons, or will you be handling that by using the source files? (Maybe this conversation should be moved somewhere else if it gets more involved).

BTW, thanks for the tips, but I'm just wondering what your preference of .svg over .ai is?

**Comment by dreamnet** [comment]
@MagnaMike No, the script(s) are just little helpers, especially for me, because I always make three icon sizes (@2x, ~ipad@2x and @3x) and I was tired of inserting in a new layer, resize,  copy the glasklart style, save the icon...... and this always three times. The scripts I made are [here](https://github.com/dreamnet/Glasklart_PScripts). If someone wants to use it, good, if not - not. :wink:
I have to say, that these scripts are very, very simple. There is no error checking (e.g. for wrong source files) or something like that, so be careful if you want to give it a try.

I am prefering .svg files simply because they are MUCH smaller than .ai files and they are compatible to many other vector programs. [SVG](http://en.wikipedia.org/wiki/Scalable_Vector_Graphics) is also some kind of "web standard" and they can be viewed in most browsers without having any special programs installed.  There is no need for ai or eps, because the source files are simply black/transparent without any special effects or something like that.

**Comment by MagnaMike** [comment]
@dreamnet Okay. Yeah they are helpful, I've used them before on other projects. 

Wow, I just compared an .ai to a .svg and the size difference is huge! Good to know, thanks.

**Comment by kieman** [comment]
Hey, could anyone made an icon for the Cydia app called "Fake Email" i dont know how i open an issue with cydia apps

**Comment by MagnaMike** [comment]
@kieman Here's a guide: [How to Request a Cydia Icon](https://github.com/glasklart/hd/wiki/How-to-Request-a-Cydia-Icon) 

Also, in the future, this isn't the best way to ask questions because this issue is just for an icon request on an unrelated app. You would be better off asking general questions in #1323 :wink:

**Comment by dreamnet** [comment]
@MagnaMike I think there is enough conversation in this issue - I'm going to add the icon and closing this. If you have any other questions, let's talk in #1323.

**Comment by Gwai** [comment]
Hello,

sorry, but the bundle identifyer is wrong, correctly it must be "com.if0rce.AirBlueSharing"
