### ISSUE TITLE
Deer Hunter 2014

### ISSUE THREAD

**Issue by ivanov007** [glasklart/hd#3809]
**App Name:** Deer Hunter 2014
**Bundle ID:** com.glu.deerhunt2
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=583222866">583222866</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deer-hunter-2014/id583222866?mt=8&uo=4">https://itunes.apple.com/us/app/deer-hunter-2014/id583222866?mt=8&uo=4</a>
**App Version:** 2.11.6
**Seller:** Glu Games Inc
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/glu-games-inc/id284419051?uo=4>© Glu Games Inc</a>
**Supported Devices:** iPhone-3GS, iPhone4, iPodTouchFourthGen, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple69/v4/07/66/9d/07669dc4-3a17-bfe4-dfe5-a8885be73cc5/source/1024x1024bb.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15972282/d28633d8-2f3d-11e6-9ab4-4882b9fe1dc5.png)

**Comment by Anuskuss** [comment]
Update?

**Comment by Trubbel** [comment]
What about something like this?

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/15972282/d28633d8-2f3d-11e6-9ab4-4882b9fe1dc5.png)
https://cloud.githubusercontent.com/assets/10730122/15972282/d28633d8-2f3d-11e6-9ab4-4882b9fe1dc5.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/15972357/5f216d9e-2f3e-11e6-8427-68c1723ce563.png

**Comment by Anuskuss** [comment]
@Trubbel This actually looks really nice and would make it easier to create one for #7430 too.

**Comment by ivanov007** [comment]
agree, also no matter if the icon changes in the future... well unless the year changes but it will be just a minor change

**Comment by Anuskuss** [comment]
@Trubbel Did the design change or why doesn't it look exactly like 2016?

**Comment by Trubbel** [comment]
@Anuskuss Because their logos doesn't look the same.

[Deer Hunter 2014 logo](http://a2.mzstatic.com/us/r30/Purple5/v4/ba/e1/5e/bae15e99-3063-f3a4-107c-d8614ac0e898/screen640x640.jpeg)
<a target="_blank" href="https://itunes.apple.com/us/app/deer-hunter-2014/id583222866?mt=8&uo=4">https://itunes.apple.com/us/app/deer-hunter-2014/id583222866?mt=8&uo=4</a>
(Last image on the site)

[Deer Hunter 2016 logo](http://a1.mzstatic.com/us/r30/Purple30/v4/39/59/ac/3959acda-fa54-c1cd-6c3f-edc259fe577c/screen322x572.jpeg)
<a target="_blank" href="https://itunes.apple.com/us/app/deer-hunter-2016/id893372761?mt=8&uo=4">https://itunes.apple.com/us/app/deer-hunter-2016/id893372761?mt=8&uo=4</a>
(Last image on the site)

**Comment by Anuskuss** [comment]
Ah, right.

**Comment by Anuskuss** [comment]
@Trubbel I saw your source and would like to add my opinion:
Could you make the space between DEE**R H**UNTER white so it creates a line over the characters (also between **DE**ER HUNTER) and maybe make the DEER HUNTE**R** end rounder?
