### ISSUE TITLE
AppCake

### ISSUE THREAD

**Issue by scottbuckley** [glasklart/hd#508]
**App Name:** AppCake
**Bundle ID:** appcake2.iphonecake.com
**Version:** 4.96
 **iTunes ID:** none (Cydia app)
 **Original Artwork:**
 <img src="https://cloud.githubusercontent.com/assets/2068130/11014359/07fbde2e-8533-11e5-8fd2-eba821a194e2.png" width="150" height="150" />
 **Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10439324/781544ba-7139-11e5-8041-4b98a3adfe0c.png)

**Comment by dreamnet** [comment]
Icon needs an update.

**Comment by dreamnet** [comment]
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10439324/781544ba-7139-11e5-8041-4b98a3adfe0c.png)
https://cloud.githubusercontent.com/assets/2068130/10439324/781544ba-7139-11e5-8041-4b98a3adfe0c.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/2068130/10439335/87aa29e0-7139-11e5-8b58-db29115cc0ca.png

**Comment by Trubbel** [comment]
Few things that needs to be updated, 

* The name changed back to AppCake 
* Bundle ID is now `com.iphonecake.appcake5`
* Artwork also changed

Since I still can't get my head around Illustrator.. :blush:
..here's the highest resolution of the artwork in the AppCake folder,
https://cloud.githubusercontent.com/assets/10730122/10926389/37bfb3f4-8297-11e5-9f45-ea65252661f7.png

**Comment by dreamnet** [comment]
This one drives me nuts... so `appcake2.iphonecake.com` isn't used anymore? Version 5.0?

**Comment by Trubbel** [comment]
@dreamnet Okay, now I am confused as well. I saw the AppCake newest update on Cydia and I downloaded it. However I can't find out which repo it is on because all it says when I'm searching for it on Cydia is: `from Unknown / Local (Utilities)` and the author is `haily`

However here's their official thread about it, "[AppCake 5 beta is on our repo, we need your FEEDBACK!](https://forum.iphonecake.com/index.php?/topic/245803-appcake-5-beta-is-on-our-repo-we-need-your-feedback/)"

And on `cydia.iphonecake.com` I can only see `AppCake for iOS6`. It's funny because I don't have their beta repo installed so I have no idea what's happening.. :laughing:

**Comment by Trubbel** [comment]
The AppCake 5 seems to be back on their repo _(at least for me?)_, anyone double check?

**Comment by dreamnet** [comment]
It's always weird to add beta apps...
To remove the confusion, this is the issue for AppCake 4.96 (`appcake2.iphonecake.com`). We need to open a new issue for AppCake 5.

**Comment by dreamnet** [comment]
No further actions needed for this one, icon already in the master.
