### ISSUE TITLE
Glasklart settings?

### ISSUE THREAD

**Issue by andreolidavide** [glasklart/hd#5100]
Why isn't this a thing yet? I'm making some icons for myself in two styles, light and dark (with preview's background).
Here are some screenshots (white background: normal settings; black background: Eclipse 2)
Light with white background
https://cloud.githubusercontent.com/assets/10515074/5909381/5b95a1cc-a5b0-11e4-98c6-bec86b98c609.PNG
Dark with white background
https://cloud.githubusercontent.com/assets/10515074/5909405/9ede3eee-a5b0-11e4-9dbb-c95d9693bfd1.PNG
Light with black background
https://cloud.githubusercontent.com/assets/10515074/5909430/d493c518-a5b0-11e4-8dcb-a16aa1df6b5d.PNG
Dark with black background
https://cloud.githubusercontent.com/assets/10515074/5909410/aec7d8e2-a5b0-11e4-88f6-2683a1de9cf9.PNG
So, is there any particular reason if Settings.app is still not themed? Can't we do it?

**Comment by MagnaMike** [comment]
It used to be a thing #1119, but it got broken with new versions of iOS. Are those working, on-device previews? If not I don't now if it's technically possible (sorry, don't have an iDevice anymore).

Calling @dreamnet &@ivanov007 !

**Comment by andreolidavide** [comment]
@MagnaMike yes, they are actual screenshots of my phone. I put 58x58@2x images in a bundle named com.apple.Preferences. I read icon names from other themes which I knew they supported settings (like ayeris or Amber).

**Comment by dreamnet** [comment]
Sure thing, theming the settings is possible again with themelib. But be warned, there will be hundreds and hundreds of icons to do do. Many apps puts themself in settings, so this will be endless work. You also have to know all the right icon names. I definitly don't have the time to do it.
@andreolidavide If you really want to do this, we have to discuss first how to do it. The noised icon background should be removed. Here is the baseplate:
![unbenannt-1](https://cloud.githubusercontent.com/assets/2068130/5926804/2093b0be-a66e-11e4-8f96-23e21a050c39.png)
P.S.: How did you make the settings background dark?

**Comment by andreolidavide** [comment]
@dreamnet I used the noised background because it is difficult to see normal icons on the white background of normal settings app. The dark backgroung in settings is done with Eclipse, but you can also use Nightmode. To solve the visibility problem I thought of two version of the theme, one made just by normal icon resized, the other one made by normal icon with a background to improve visibility (I use the noised but we can use plain black maybe).
It is a lot of work but for the "Light" version we can just resize icons that are already done.
Anyway I don't think I can take on the responsibility of this just by myself. If you tell me which guidelines i should follow, I'll start by making all the stock icons. Then you will tell me if this "project" should continue or not.

**Comment by dreamnet** [comment]
@andreolidavide Theming the stock icons is not the problem and I think it dosen't look bad if we downsize the existing icons. But there are so many other apps out there and this always would lead us to just half themed settings. I don't think this would be good for Glasklart.
Also: If I have it right, to use "Nightmode" on iPhone without any other tweaks I must go to Settings -> General -> Accessibility and then select Invert Colors. But this will invert allmost everything, so in my oppinion it's not necessary to make extra icons for this. Try it out!
If we really do this, we should go in the "Dark with white background"-direction from your screenshot above.
@glasklart/maintainers Any thoughts?

**Comment by andreolidavide** [comment]
@dreamnet I was talking of the tweak named Nightmode (it is basically the same of Eclipse), not a setting.
Ok I get what you mean, you're right, it is probably a too big task. That's a pity, but half theming would look bad, you're right on that too.

**Comment by dreamnet** [comment]
@andreolidavide Don't get me wrong, I really would love to see the settings themed....
But especally for the way Glasklart is looking, many users would get just half themed and because of that bad looking settings, so I think its better to leave that out... at the moment. :cry: 
But I keep it in mind.

**Comment by MagnaMike** [comment]
A couple of things:
 - We used a noised background before so I don't see the problem with repeating that look if we are going with a white background
 - What names are used to theme these icons? How hard are they to find?
 - Making the icons themselves is a non-issue because as @dreamnet said we can scale them down (and add a noised background), with a Photoshop script
 - As long as we can find the icon names easily, then in my opinion having un-themed icons is not a problem because they will also be un-themed on the Springboard and it is the same situation, just need an icon request to solve the problem as usual
 - I think there should only be one style (no dark and light versions), just for simplicity, and ideally without any extra tweaks
 - I don't have a device so I can't help much here other then making icons

The main issue to me is whether or not the icon names can easily be found for existing icons, and incorporated with every icon request for new icons. If we can't get the names easily, then it's not the time in my opinion. It would look nice though. :heart_eyes:

**Comment by andreolidavide** [comment]
@MagnaMike I found the names of these icons by copying them from a working theme, and they all goes by this pattern SettingName@2x.png (examples: Display@2x.png; AppStore@2x.png; FacebookSettings@2x.png; iCloud@2x.png).
This work with stock apps and settings, I don't actually know if third party apps have their setting icons in com.apple.Preferences or in their own bundle. If they have it in their own bundle then all this is a no go, because it would mean a lot of work, creating a bundle for every icon and searching every name in Info.plist files. I'll look into this, but @dreamnet has a point, we may better leave this out for the moment, if we don't find an easy way to overcome the naming/bundles problem.

**Comment by dreamnet** [comment]
[Here](http://junesgraphics.blogspot.co.at/2014/11/themelib-tutorial-theme-statusbar-clock.html#.VMlqpmiG98E) are some totorials and examples what can be done with themelib at the moment.

**Comment by dreamnet** [comment]
OK, we leave it out for the moment until someone finds a simple way to theme the non-stock settings icons.
