### ISSUE TITLE
Goat Simulator

### ISSUE THREAD

**Issue by PolarisBeaver** [glasklart/hd#5155]
**App Name:** Goat Simulator
**Bundle ID:** com.coffeestainstudios.goatsimulator
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=868692227">868692227</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/goat-simulator/id868692227?mt=8&uo=4">https://itunes.apple.com/us/app/goat-simulator/id868692227?mt=8&uo=4</a>
**App Version:** 1.1.1
**Seller:** Coffee Stain Studios AB
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/coffee-stain-studios/id424598022?uo=4>© Coffee Stain Studios</a>
**Supported Devices:** iPad2Wifi, iPodTouchFourthGen, iPhone5, iPhone4S, iPadThirdGen4G, iPadFourthGen, iPhone4, iPadMini4G, iPhone6, iPadThirdGen, iPadFourthGen4G, iPad23G, iPhone6Plus, iPadMini, iPhone5c, iPodTouchFifthGen, iPhone-3GS, iPhone5s
**Original Artwork:**
<img src="http://a1269.phobos.apple.com/us/r30/Purple3/v4/e3/b9/cd/e3b9cdad-ddd1-f804-5f15-5c00d89c8060/mzl.iwmqwsnm.jpg" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6091504/817f331e-aeaf-11e4-86c0-2c29fc5ea273.png)

**Comment by PolarisBeaver** [comment]
Anyone up for the challenge? I honestly have no idea how to do photos, I'm only good with flat graphics.

**Comment by dreamnet** [comment]
Because this is one of those nearly-complete-impossible-to-do icons, we could do something like this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/6091504/817f331e-aeaf-11e4-86c0-2c29fc5ea273.png)
https://cloud.githubusercontent.com/assets/2068130/6091504/817f331e-aeaf-11e4-86c0-2c29fc5ea273.png
Source:
https://cloud.githubusercontent.com/assets/2068130/6091505/936b68b8-aeaf-11e4-878c-148a028381f4.png

**Comment by PolarisBeaver** [comment]
@dreamnet I like it!

**Comment by MagnaMike** [comment]
@dreamnet @PolarisBeaver Agreed. :+1:
