### ISSUE TITLE
YoBu

### ISSUE THREAD

**Issue by Gwai** [glasklart/hd#5340]
**App Name:** YoBu
**Bundle ID:** Hachi.YoBu
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=947452765">947452765</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/yobu/id947452765?mt=8&uo=4">https://itunes.apple.com/us/app/yobu/id947452765?mt=8&uo=4</a>
**App Version:** 1.3
**Seller:** Harshdeep Singh
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/harshdeep-singh/id838658908?uo=4>© Harshdeep Singh</a>
**Supported Devices:** iPadMini, iPadThirdGen, iPadThirdGen4G, iPhone4S, iPodTouchFifthGen, iPadFourthGen4G, iPadMini4G, iPhone6Plus, iPad2Wifi, iPhone6, iPadFourthGen, iPhone5s, iPhone5, iPhone5c, iPad23G
**Original Artwork:**
<img src="http://a763.phobos.apple.com/us/r30/Purple3/v4/82/29/27/8229279d-3443-c15e-046c-d952ccac311b/mzl.htsmrivz.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6660079/61bdc650-cb68-11e4-9733-15a742fc5ff9.png)

**Comment by zmathiasz** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10950389/6659722/d70e4eea-cb61-11e4-9f59-707f34bf8834.png)
https://cloud.githubusercontent.com/assets/10950389/6659722/d70e4eea-cb61-11e4-9f59-707f34bf8834.png
Source:
https://cloud.githubusercontent.com/assets/10950389/6659728/e2fc5c92-cb61-11e4-8176-93fe41f3eeb3.png

**Comment by MagnaMike** [comment]
I did it in illustrator to make a cleaner one since the artwork wasn't very good quality.
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/2236254/6660079/61bdc650-cb68-11e4-9733-15a742fc5ff9.png)
https://cloud.githubusercontent.com/assets/2236254/6660079/61bdc650-cb68-11e4-9733-15a742fc5ff9.png

---
Source:
https://cloud.githubusercontent.com/assets/2236254/6660083/79cb0b22-cb68-11e4-8ecd-f12cf8ab54d2.png

**Comment by zmathiasz** [comment]
Works for me. In the process of learning illustrator. :)

**Comment by MagnaMike** [comment]
Me too :stuck_out_tongue:
