### ISSUE TITLE
Deutsch-Englisch Wörterbuch

### ISSUE THREAD

**Issue by Hack4Life** [glasklart/hd#5547]
**App Name:** Deutsch-Englisch Wörterbuch
**Bundle ID:** la.bab.german.deendict
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=346185555">346185555</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/deutsch-englisch-worterbuch/id346185555?mt=8&uo=4">https://itunes.apple.com/us/app/deutsch-englisch-worterbuch/id346185555?mt=8&uo=4</a>
**App Version:** 3.0
**Seller:** bab.la GmbH
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/bab.la-gmbh/id346185558?uo=4>© bab.la GmbH</a>
**Supported Devices:** iPadFourthGen, iPadMini, iPad23G, iPhone4, iPhone5c, iPad2Wifi, iPodTouchFourthGen, iPadThirdGen, iPhone4S, iPadMini4G, iPhone-3GS, iPadFourthGen4G, iPhone6Plus, iPodTouchThirdGen, iPhone5s, iPadWifi, iPhone5, iPad3G, iPodTouchFifthGen, iPhone6, iPadThirdGen4G
**Original Artwork:**
<img src="http://a321.phobos.apple.com/us/r30/Purple2/v4/dc/aa/37/dcaa3767-bf68-8927-0586-38fc9851f83c/mzl.zesgwngm.png" width="150" height="150" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7248023/46ad43e8-e7d5-11e4-8818-5e2c13043de4.png)

**Comment by ivanov007** [comment]
since german and russian flags will look the same I think the text on the bottom will be needed
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/7248023/46ad43e8-e7d5-11e4-8818-5e2c13043de4.png)
https://cloud.githubusercontent.com/assets/3090247/7248023/46ad43e8-e7d5-11e4-8818-5e2c13043de4.png

---
Source:
https://cloud.githubusercontent.com/assets/3090247/7248036/5e1b1d66-e7d5-11e4-90b9-0ec325602806.png

**Comment by dreamnet** [comment]
@ivanov007 Jep, that's it, good idea! :+1:
