### ISSUE TITLE
Eggsquis

### ISSUE THREAD

**Issue by LaCh0uine** [glasklart/hd#5885]
**App Name:** Eggsquis
**Bundle ID:** com.keybook.eggsquisapp
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=606393705">606393705</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/eggsquis/id606393705?mt=8&uo=4">https://itunes.apple.com/us/app/eggsquis/id606393705?mt=8&uo=4</a>
**App Version:** 4.0.2
**Seller:** Mobile Marketing Media Inc.
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/artist/mobile-marketing-media/id477440985?uo=4>© Mobile Marketing Media</a>
**Supported Devices:** iPad2Wifi, iPad23G, iPhone6Plus, iPhone5c, iPhone-3GS, iPadMini, iPodTouchFourthGen, iPhone5, iPhone5s, iPadMini4G, iPhone4, iPadThirdGen4G, iPodTouchFifthGen, iPadFourthGen, iPhone6, iPadFourthGen4G, iPhone4S, iPadThirdGen
**Original Artwork:**
<img src="http://is2.mzstatic.com/image/pf/us/r30/Purple1/v4/ac/58/16/ac5816cb-ee80-e584-407b-156e39394010/mzl.qhbqrzio.png" width="150" height="150" />
**Accepted Artwork:**
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8530949/60149030-2424-11e5-904f-dfc2a6c3e901.png)

**Comment by ivanov007** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/3090247/8504996/1b776522-21a1-11e5-811f-308ccd3102c6.png)
https://cloud.githubusercontent.com/assets/3090247/8504996/1b776522-21a1-11e5-811f-308ccd3102c6.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/3090247/8504995/1a71292e-21a1-11e5-8066-771fb8a9c8b8.png

**Comment by dreamnet** [comment]
Centering the "Eggsquis" text, because the small text under it is leaved out...
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8530949/60149030-2424-11e5-904f-dfc2a6c3e901.png)
https://cloud.githubusercontent.com/assets/2068130/8530949/60149030-2424-11e5-904f-dfc2a6c3e901.png

---
Source:
https://cloud.githubusercontent.com/assets/2068130/8530958/6fb5d72e-2424-11e5-972b-ea2875f0fc48.png
