### ISSUE TITLE
DataMan Pro

### ISSUE THREAD

**Issue by pitrepo** [glasklart/hd#5911]
**App Name:** DataMan Pro
**Bundle ID:** com.xvision.datamanpro9
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=807571009">807571009</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/dataman-pro/id807571009?mt=8&uo=4">https://itunes.apple.com/us/app/dataman-pro/id807571009?mt=8&uo=4</a>
**App Version:** 12.0
**Seller:** Johnny Ixe
**Developer:** <a target="_blank" href=https://itunes.apple.com/us/developer/johnny-ixe/id326568233?uo=4>© Johnny Ixe</a>
**Supported Devices:** iPhone4S, iPhone5, iPhone5c, iPhone5s, iPhone6, iPhone6Plus
**Original Artwork:**
<img src="http://is1.mzstatic.com/image/thumb/Purple60/v4/50/8a/0f/508a0f4d-a6dc-f740-9eb8-be41753da5b7/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![-large](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/18797829/18dee3ae-81d0-11e6-8d38-c2535ed7945d.png)

**Comment by Trubbel** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/10730122/8524327/d131779e-23fa-11e5-8583-348c2e1faf8b.png)
https://cloud.githubusercontent.com/assets/10730122/8524327/d131779e-23fa-11e5-8583-348c2e1faf8b.png
--- ---
Source:
https://cloud.githubusercontent.com/assets/10730122/8524324/cdcc039e-23fa-11e5-9798-d9b074f103c2.png

**Comment by dreamnet** [comment]
@Trubbel Good work, but the source file is too big....

**Comment by Trubbel** [comment]
@dreamnet You want it to be like this - 
https://cloud.githubusercontent.com/assets/10730122/8532176/b01c499e-242c-11e5-9eab-b581c0b7e806.png?

**Comment by dreamnet** [comment]
@Trubbel The 1024x1024px of the source file representing the 78x78px area in the glasklart file.
If I take your first source, the result is this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8532266/370923b4-242d-11e5-9613-88e166b7bc5d.png)
If I take you second source, the result is this:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8532289/6636e8ba-242d-11e5-91d3-72b3737bee7a.png)
The first one is too big and the second one too small.

This source file is correct:
https://cloud.githubusercontent.com/assets/2068130/8532354/e89a4df6-242d-11e5-992e-1e6fce04260d.png
If I use this source file, I get this result:
![2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/8532372/0154044a-242e-11e5-881c-b107ac2cc5db.png)
In this icon, the triangles are having exactly the same size as the 120px original icon - you can compare it [here](http://glasklarthd.dreamnet.at/index.php?id=7980).

We are doing this, because it is possible the Apple are changing icon sizes in the future and with this sources, we are able to resize them with a script, so we don't have to redo all the Glasklart icons by hand.

**Comment by Trubbel** [comment]
@dreamnet Okay, now I understand, I'll keep this in mind. Thanks!

**Comment by dreamnet** [comment]
@Trubbel No problem! :+1:

**Comment by ivanov007** [comment]
needs update

**Comment by dreamnet** [comment]
@ivanov007 Already in [the master](https://github.com/glasklart/hd/blob/master/Library/Themes/Glasklart%20Icons.theme/IconBundles/com.xvision.datamanpro9-large.png). ?

**Comment by dreamnet** [comment]
No action needed - closing.
