### ISSUE TITLE
Stock App Icon Updates?

### ISSUE THREAD

**Issue by alpcinar** [glasklart/hd#6546]
Passbook still using the iOS 7 styled icon.
Also: Videos & Game Center

**Comment by dreamnet** [comment]
@alpcinar Comparsion (iOS7 - iOS8 - Glasklart):
Passbook:
![com apple passbook_120](https://cloud.githubusercontent.com/assets/2068130/10386546/ebe35032-6e58-11e5-90ac-15f4c1659c08.png) ![passbook_ios8](https://cloud.githubusercontent.com/assets/2068130/10386548/f383193a-6e58-11e5-93ac-32b0915a4e5e.png) ![com apple passbook 2x](https://cloud.githubusercontent.com/assets/2068130/10386570/215d59b0-6e59-11e5-8c48-cd2e14e8e7b6.png)
There is just one tab more between the iOS7 and the iOS8 stock icon, so we decided to keep the iOS7 Glasklart icon, because the small icons in the iOS8-stock-version would be too small in the finished Glasklart icon.
--- ---
Videos:
![com apple videos_120](https://cloud.githubusercontent.com/assets/2068130/10386611/cee87c40-6e59-11e5-8bcd-565d2f3d8ee7.png) ![videos_ios8](https://cloud.githubusercontent.com/assets/2068130/10386612/d4841cc2-6e59-11e5-8566-4697c5eb82d1.png) ![com apple videos 2x](https://cloud.githubusercontent.com/assets/2068130/10386618/e5bdf1c0-6e59-11e5-8902-785524c9952c.png)
No difference between the iOS7 and the iOS8 stock icons, we kept the old iOS6 style icon for Glasklart - I think you are right, we should update this.
--- ---
Game Center:
![com apple gamecenter_120](https://cloud.githubusercontent.com/assets/2068130/10386701/c60ffdc2-6e5a-11e5-93fc-7e97c06cdd64.png) ![gamecenter_ios8](https://cloud.githubusercontent.com/assets/2068130/10386709/ce8c1a44-6e5a-11e5-876a-aaf3be1c2f7a.png) ![com apple gamecenter 2x](https://cloud.githubusercontent.com/assets/2068130/10386714/db482a98-6e5a-11e5-8835-ae6bdb517654.png)
The stock Game Center icon for iOS7 and iOS8 are the same and they are... ähhh... ugly, but I also think we should update it.

**Comment by dreamnet** [comment]
OK, I carefully made some new ones:
![Passbook](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10413741/03efc02c-6fb5-11e5-8edc-e21fa0d6b499.png)![Videos](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10413745/2028417e-6fb5-11e5-857f-c3a841d91423.png)![GameCenter](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10413749/3319a480-6fb5-11e5-8d34-91fbb61c4537.png)
What ya think?

**Comment by ivanov007** [comment]
I just updated to iOS9 and passbook now is called Wallet, also the icon changed a lot not sure if I need to open a new issue or use the already open #653 it's quite old post but couldn't find any other

**Comment by dreamnet** [comment]
@ivanov007 I also updated to iOS9 and I already made an icon for "Wallet", but I cannot integrate it, because I can't find a "Wallet"-app, in the iOS9 system it still has the Bundle ID `com.apple.Passbook` and it's still called Passbook so I'm a bit confused about this and I leaved the the "Passbook" icon as it is above - maybe this has something todo with the country I live?
Here is the Wallet icon:
![com apple wallet 2x](http://preview.dreamnet.at?image=https://cloud.githubusercontent.com/assets/2068130/10695776/d495e108-79a5-11e5-8742-2b762156bccd.png)
I don't know if I should change `com.apple.Passbook` to the new icon, because we are compatible to iOS8 and iOS7.....

**Comment by ivanov007** [comment]
@dreamnet well it seems we'll face another hard decision 
http://www.iphonefaq.org/archives/974588

**Comment by dreamnet** [comment]
@ivanov007 Yes. On the other side - why not updating the icon? Users users of iOS7 or 8 can became accustomed with the new icon before updating to iOS9... I think I will do it.

**Comment by dreamnet** [comment]
@ivanov007 Done.

**Comment by dreamnet** [comment]
Also updating iBooks in #4046...

**Comment by dreamnet** [comment]
New Podcasts icon is in #4794....

**Comment by ivanov007** [comment]
@dreamnet where did you get the original sources? from your device?

**Comment by dreamnet** [comment]
@ivanov007 Yes... :smile:

**Comment by LaCh0uine** [comment]
ICloud Drive too need icon ;)

**Comment by dreamnet** [comment]
@LaCh0uine #6711 iCloud Drive is in the next release.

**Comment by LaCh0uine** [comment]
@dreamnet awesome ;)

**Comment by dreamnet** [comment]
I think we are done with this for now, so I'm closing it.
