### ISSUE TITLE
[Question] Theming WebClips

### ISSUE THREAD

**Issue by Anuskuss** [glasklart/hd#7158]
Is it possible to theme WebClips? I ask because there is an "app" named [Mojo Installer](https://mojoinstaller.co), and it installs a web clip which would look nicer if it had the Glasklart feeling.

**Icon:**
![](http://mojoinstaller.co/mojo_files/app_icon@2x.png)

**Comment by Trubbel** [comment]
Yes it is possible indeed. Using the `Folders`-method. However, it seems like a dark underlay is added behind them, even when you manually change the icon. Not quite sure how to fix that.

If you're interested however, this is how you theme it;

`/Folders/<bunch-of-random-characters>.webclip/icon.png`
_(It's 839B39505B384B1596C431B7074265BB.webclip for me)_
 

To theme it manually _(same dark underlay outcome)_;

Use [iFunbox](http://www.i-funbox.com/) or something similar and navigate to `//private/var/mobile/Library/WebClips/839B39505B384B1596C431B7074265BB.webclip` and then replace the icon file with this [one](https://cloud.githubusercontent.com/assets/10730122/12641170/484291f6-c5ae-11e5-9a69-90c562921063.png).

**Comment by Anuskuss** [comment]
Is there a way to theme by name? So that you could actually include it in the Glasklart theme.

**Comment by Trubbel** [comment]
Well, `/Icons/icon.png` might work, because the icons name is just "icon", so I'm pretty sure it wont work if you use the Web Clips' name. I can't test this right now though.

I'm honestly not sure if @coolstar can do anything about it, hopefully he can answer that. :wink: 

If it does get fixed, I'm pretty sure we can support the more popular Web Clips like this one.

**Comment by dreamnet** [comment]
Closing, until a solution is found.
