### ISSUE TITLE
Trailforks

### ISSUE THREAD

**Issue by BBenC** [glasklart/hd#8663]
**App Name:** Trailforks - Mountain Bike Trail Map
**Bundle ID:** com.pinkbike.trailforks
**iTunes ID:** <a target="_blank" href="http://getart.dreamnet.at?id=987986743">987986743</a>
**iTunes URL:** <a target="_blank" href="https://itunes.apple.com/us/app/trailforks-mountain-bike-trail/id987986743?mt=8&uo=4">https://itunes.apple.com/us/app/trailforks-mountain-bike-trail/id987986743?mt=8&uo=4</a>
**App Version:** 1.8
**Seller:** Fireroad Holdings Inc
**Developer:** <a target="_blank" href="https://itunes.apple.com/us/developer/pinkbike.com/id957531783?uo=4">© Pinkbike.com</a>
**Supported Devices:** iPhone4, iPad2Wifi, iPad23G, iPhone4S, iPadThirdGen, iPadThirdGen4G, iPhone5, iPodTouchFifthGen, iPadFourthGen, iPadFourthGen4G, iPadMini, iPadMini4G, iPhone5c, iPhone5s, iPhone6, iPhone6Plus, iPodTouchSixthGen
**Original Artwork:**
<img src="http://is4.mzstatic.com/image/thumb/Purple71/v4/82/f3/98/82f39874-cf07-3483-4f5c-36f22d2993a2/source/1024x1024bb.png" width="180" height="180" />
**Accepted Artwork:**
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20398826/31441708-acef-11e6-9d58-61062946a22d.png)

**Comment by BBenC** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23527161/20395763/e9c780d0-acdb-11e6-855b-e6a18616e38d.png)
https://cloud.githubusercontent.com/assets/23527161/20395763/e9c780d0-acdb-11e6-855b-e6a18616e38d.png
Source:
https://cloud.githubusercontent.com/assets/23527161/20396003/ae60111e-acdc-11e6-86ed-04921895c2ea.png

Hopefully I've done this correctly, if not let me know what I've done wrong before I attempt another one.
Thanks

**Comment by dreamnet** [comment]
@BBenC Good work! :+1: There is just one small problem with the source file: The whole 1024x1024px area in the source file represents the 118x118px area in the center of the finished icon (the lines you can see in the preview above). So the icon in the source file has to go to the edges (always keep aspect ratio) of the 1024x1024px area...
That's a bit hard to explain, so here are some examples:
[Example 1](https://github.com/glasklart/hd/issues/8650)
[Example 2](https://github.com/glasklart/hd/issues/8653)
[Example 3](https://github.com/glasklart/hd/issues/8593)
In Example 2 you can see in the [source file](https://cloud.githubusercontent.com/assets/2068130/20245818/5ec938a0-a9a9-11e6-8222-8b9364245f2d.png), that the height of the icon in it is not covering the whole 1024x1024px area, that's because the "Ball" in the original artwork is also smaller than 118x118px. In the finished Glasklart icon, the "Ball" should have the same size as in the original icon (but not larger than 118x118px).
If you have any further questions, feel free to ask. And again: Very good work on the above icon for a first try!

**Comment by BBenC** [comment]
Thanks, that makes sense. I think I have fixed the issue here.

![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/23527161/20398151/25920948-ace4-11e6-87e5-db63606486d0.png)
https://cloud.githubusercontent.com/assets/23527161/20398151/25920948-ace4-11e6-87e5-db63606486d0.png
Source:
https://cloud.githubusercontent.com/assets/23527161/20397973/7cf53724-ace3-11e6-978f-2958a8d934a4.png

**Comment by 2Qt2beStr8** [comment]
![](http://preview.dreamnet.at/?image=https://cloud.githubusercontent.com/assets/20930745/20398826/31441708-acef-11e6-9d58-61062946a22d.png)
https://cloud.githubusercontent.com/assets/20930745/20398826/31441708-acef-11e6-9d58-61062946a22d.png

Source:
https://cloud.githubusercontent.com/assets/20930745/20398848/445a0672-acef-11e6-9e6f-6bf502bfdfa3.png

**Comment by dreamnet** [comment]
@BBenC Nearly. For this one, the icon in the source file must have a withd of 1024px - as the one @2Qt2beStr8 made.
